version: '3.8'

networks:
  moto_net:
    driver: bridge

volumes:
    jenkins_home:
        external: true

services:
    jenkins:
        image: moto88/jenanssh:0.0.1
        container_name: jenkins1
        privileged: true
        user: root
        ports:
          - 8888:8080
        volumes:
          - jenkins_home:/var/jenkins_home/
          - /var/run/docker.sock:/var/run/docker.sock
          - /usr/bin/docker:/usr/bin/docker
        expose:
        - 8888
        networks:
        - moto_net
      
    tomcat:
        image: tomcat:latest
        container_name: tomcat
        #command:
         #   - '--config.file=/etc/alertmanager/config.yml'
         #   - '--storage.path=/alertmanager'
        restart: unless-stopped
        environment:
            - TOMCAT_USERNAME=admin
            - TOMCAT_PASSWORD=admin
        expose:
        - 8787
        networks:
        - moto_net